src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Session Registrations</relationshipLabel>
        <relationshipName>Session_Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Registration</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Session Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Attendee.cls
public with sharing class Attendee {

	public Attendee__c record;
	@AuraEnabled public SessionRegistration[] sessionRegistrationList;
	@AuraEnabled public String firstName;
	@AuraEnabled public String lastName;

	public Attendee(Attendee__c att) {
		this.buildFromRecord(att);
	}

	private void buildFromRecord(Attendee__c att) {
		this.record = att;
		this.firstName = att.First_Name__c;
		this.lastName = att.Last_Name__c;

		this.sessionRegistrationList = new SessionRegistration[]{};
		for (Session_Registration__c sr : att.Session_Registrations__r) {
			this.sessionRegistrationList.add(new SessionRegistration(sr));
		}
	}
}