src/objects/Attendee__c.object
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Session Registrations</relationshipLabel>
        <relationshipName>Session_Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Session Registrations</relationshipLabel>
        <relationshipName>Session_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Registration</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Session Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SessionRegistration.cls
public with sharing class SessionRegistration {
	
	public SObjectUnitOfWork uow;
	public Session_Registration__c record;
	@AuraEnabled public String sessionName;
	@AuraEnabled public DateTime sessionStart;
	@AuraEnabled public DateTime sessionEnd;
	public Session sess;
	public Attendee att;

	public SessionRegistration(Session_Registration__c sr) {
		this.buildFromRecord(sr);
	}

	public SessionRegistration(Session sess, Attendee att) {
		this.sess = sess;
		this.att = att;
	}

	public void buildFromRecord(Session_Registration__c sr) {
		this.record = sr;
		this.sessionName = sr.Session__r.Name;
		this.sessionStart = sr.Session__r.Start__c;
		this.sessionEnd = sr.Session__r.End__c;
	}

	public void upsertRecord() {
		if (this.record == null) this.record = new Session_Registration__c();
		
		this.record.Attendee__c = this.att.record.Id;
		this.record.Session__c = this.sess.record.Id;
		this.uow.registerDirty(this.record);
	}

}