src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestHelper.cls
@isTest
public with sharing class TestHelper {

	Event__c event;
	Map<String, Session__c> sessionMap;
	Attendee__c attendee;

	public Event__c createEvent(String name, Boolean toInsert) {
		event = new Event__c(Name = name);
		if (toInsert) insert event;
		return event;
	}

	public Session__c createSession(String name, Datetime sessionStart, Datetime sessionEnd, Boolean toInsert) {
		if (sessionMap == null) sessionMap = new Map<String, Session__c>();

		Session__c sess = new Session__c(
				Name = name,
				Start__c = sessionStart,
				End__c = sessionEnd,
				Event__c = event.Id
			);

		sessionMap.put(name, sess);
		if (toInsert) insert sess;
		return sess;
	}

	public Attendee__c createAttendee(String firstName, Boolean toInsert) {
		attendee = new Attendee__c(
			Event__c = event.Id,
			First_Name__c = firstName
		);
		if (toInsert) insert attendee;
		return attendee;
	}

}