src/objects/Attendee__c.object
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Session Registrations</relationshipLabel>
        <relationshipName>Session_Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Session Registrations</relationshipLabel>
        <relationshipName>Session_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Registration</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Session Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AttendeeService.cls
public with sharing class AttendeeService {

	public static void registerAttendeeForSession(Map<Id, Id[]> sessionsByAttendee) {
		Attendee__c[] attList = AttendeeSelector.getAttendeeWithSessionRegistrations(sessionsByAttendee.keySet());
		Set<Id> sessionIdSet = new Set<Id>();

		for (Attendee__c attRecord : attList) {
			for (Session_Registration__c sr : attRecord.Session_Registrations__r) {
				sessionIdSet.add(sr.Session__c);
			}
		}
		for (Id attId : sessionsByAttendee.keySet()) {
			sessionIdSet.addAll(sessionsByAttendee.get(attId));
		}

		Map<Id, Session__c> sessionMap = new Map<Id, Session__c>(SessionSelector.getSessionsById(sessionIdSet));

		for (Attendee__c attRecord : attList) {
			Attendee att = new Attendee(attRecord);
			for (Id sessionId : sessionsByAttendee.get(attRecord.Id)) {
				Session sess = new Session(sessionMap.get(sessionId));
				att.registerForSession(sess);
			}
		}
	}

	public static void validateSessionRegistration(Session_Registration__c[] srList) {
		Set<Id> attIdSet = new Set<Id>();
		Set<Id> sessIdSet = new Set<Id>();

		for (Session_Registration__c sr : srList) {
			if (sr.Attendee__c != null) {
				attIdSet.add(sr.Attendee__c);
			}
			if (sr.Session__c != null) {
				sessIdSet.add(sr.Session__c);
			}		
		}

		Map<Id, Session__c> sessionMap = new Map<Id, Session__c>(SessionSelector.getSessionsById(sessIdSet));
		Map<Id, Attendee__c> attendeeMap = new Map<Id, Attendee__c>(AttendeeSelector.getAttendeeWithSessionRegistrations(attIdSet));

		for (Session_Registration__c sr : srList) {
			if (sr.Attendee__c == null || sr.Session__c == null) continue;
			Attendee att = new Attendee(attendeeMap.get(sr.Attendee__c));
			Session sess = new Session(sessionMap.get(sr.Session__c));
			try {
				att.validateSessionRegistration(sess);
			} catch(Attendee.AttendeeException e) {
				sr.addError(e.getMessage());
			}
		}

	}
}