src/objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SessionSelector.cls
public with sharing class SessionSelector {

	public static Session__c[] getSessionsById(Set<Id> idSet) {
		Session__c[] sessList = [SELECT Name
									, Start__c
									, End__c
								FROM Session__c
								WHERE Id IN :idSet];
		return sessList;
	}

	public static Session__c[] getSessionsByEvent(Set<Id> idSet) {
		Session__c[] sessList = [SELECT Name
									, Start__c
									, End__c
								FROM Session__c
								WHERE Event__c IN :idSet];
		return sessList;
	}

}