src/objects/Session__c.object
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Session Registrations</relationshipLabel>
        <relationshipName>Session_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Registration</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Session Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Attendee_ManageSessionRegistrationsCTRL.cls
public with sharing class Attendee_ManageSessionRegistrationsCTRL {

	public Attendee attendee {get; set;}
	public SelectOption[] sessionOptions {get; set;}
	public Id selectedSessionId {get; set;}

	public Attendee_ManageSessionRegistrationsCTRL(ApexPages.StandardController ctrl) {
		this.attendee = new Attendee(AttendeeSelector.getAttendeeWithSessionRegistrations(new Set<Id>{ctrl.getId()})[0]);
		
		this.sessionOptions = new SelectOption[]{};
		for (Session__c sess : SessionSelector.getSessionsByEvent(new Set<Id>{attendee.eventId})) {
			this.sessionOptions.add(new SelectOption(sess.Id, sess.Name));
		}
	}

	public PageReference registerForSession() {
		Session sess = new Session(SessionSelector.getSessionsById(new Set<Id>{selectedSessionId})[0]);
		this.attendee.registerForSession(sess);
		return null;
	}

	public PageReference saveRegistrations() {

		SObjectUnitOfWork uow = new SObjectUnitOfWork(new Schema.SObjectType[]{Session_Registration__c.SObjectType});				
		this.attendee.uow = uow;
		this.attendee.upsertSessionRegistrationRecords();
		uow.commitWork();

		PageReference pr = new PageReference('/' + this.attendee.recordId);
		pr.setRedirect(true);
		return pr;
	}
}